### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by Shinso33** [Blockchair/Deleted-Issues#176]
Txid: 5f0734845ae65d1283a11007f79bd6b3dbc0f0efd87c4916f1252e4f9e530e65
sender address: DPinjPHr3rSnc4BQFYaudTGb8oQhRcnUqn

recipient address: DLiCqJNq1sdDRHg8Q11XDYcgzMX8Q6CVSq

I haven't paid for 24 hours Pls help me

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please refer to the [FAQ page](https://blockchair.com/faq).

**Comment by Shinso33** [comment]
9 Mar 2021 Sal, saat 20:20 tarihinde daria-blockchair <
notifications@github.com> şunu yazdı:
