### ISSUE TITLE
Has not been Confirmed

### ISSUE THREAD

**Issue by hasan1910** [Blockchair/Deleted-Issues#177]
Hello,
Yestarday I want to send doge coin from paribu wallet to binance wallet. But this operation has not confirmed yet. Pls help me and say what time confirmed my sending operation ? If you want I will write TXID. I’m waiting.

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please refer to the [FAQ (Q1) page](https://blockchair.com/faq).
