### ISSUE TITLE
I've waited more than 12 hours for a doge coin transaction and I m still waiting. > txid

### ISSUE THREAD

**Issue by osmankutuk18** [Blockchair/Deleted-Issues#178]
> I've waited more than 12 hours for a doge coin transaction and I m still waiting.
> txid

https://blockchair.com/dogecoin/transaction/5f0734845ae65d1283a11007f79bd6b3dbc0f0efd87c4916f1252e4f9e530e65

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please refer to the [FAQ (Q1)](https://blockchair.com/faq) page.

**Comment by Shinso33** [comment]
9 Mar 2021 Sal, saat 20:22 tarihinde osmankutuk18 <notifications@github.com>
şunu yazdı:
