### ISSUE TITLE
Doge Kazım Sitesi 

### ISSUE THREAD

**Issue by Kuralsiz016** [Blockchair/Deleted-Issues#180]
Dogex, stydox tarzı site güzel siteye benziyor telegram grubu filan var
Minimum yatırım 300 doge 
Min çekim 100 doge 
Yatirdiginiz tutarı 10 günde amorti ediyor sonrası kar
Katılmak isteyenler Refim ile katılırsa memnun olurum
Kesinlikle yatırım tavsiyesi değildir kullanmak isteyenler için dir

https://bitvella.com?r=nDVwxZ

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please refer to our [FAQ page](https://blockchair.com/faq).
