### ISSUE TITLE
Not confirmed ,why?

### ISSUE THREAD

**Issue by tayfunbinici** [Blockchair/Deleted-Issues#185]
![Screenshot_20210309-061159](https://user-images.githubusercontent.com/80307310/110424308-a58e4d80-80b3-11eb-8de9-0d83860c2508.jpg)
![Screenshot_20210309-061218](https://user-images.githubusercontent.com/80307310/110424313-a6bf7a80-80b3-11eb-9843-3679655755cf.jpg)
why is it approved?  It took too long to send this doge

**Comment by ozankaya4111** [comment]
Geri yatar mı yoksa gittimi dogeler

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. Please refer to our [FAQ (Q1)](https://blockchair.com/faq).

**Comment by Shinso33** [comment]
Bendede ayni sorun
