### ISSUE TITLE
Onaylanmamış transfer

### ISSUE THREAD

**Issue by aslannnnn** [Blockchair/Deleted-Issues#186]
09f45c4b8313d4561e4c52b81247bee035935434d83b798178adb7970249f884 txıd kodlu transferim 27 saat oldu hala onaylanmamış daha ne kadar sürecek kimse bilgi vermiyor en fazla kaç gün sürüyor zaman aşımı var mı biri bilgi verirse sevinirim

**Comment by daria-blockchair** [comment]
Blockchair does not process transactions. Please refer to our [FAQ (Q1)](https://blockchair.com/faq)
