### ISSUE TITLE
I've waited more than 12 hours for a doge coin transaction. 

### ISSUE THREAD

**Issue by axt4** [Blockchair/Deleted-Issues#189]
I've waited more than 12 hours for a doge coin transaction and I m still waiting.
txid
6e1e539854393b37a7c2063d215c1e5dff8cd2de29d383ca4b23c8d3eefb35bf

**Comment by daria-blockchair** [comment]
Blockchair does not process transactions. Please refer to our [FAQ (Q1)](https://blockchair.com/faq).
