### ISSUE TITLE
Зависла транзакция что делать

### ISSUE THREAD

**Issue by Alex777Ale** [Blockchair/Deleted-Issues#192]
![Без названия](https://user-images.githubusercontent.com/79548843/109404476-9ecc5000-79ba-11eb-891d-1d2340a2c5f0.png)

**Comment by daria-blockchair** [comment]
Blockhair только показывает информацию о транзакциях, которые произошли в блокчейнах. Мы не предоставляем услуги кошелька, не обрабатываем транзакции и не храним ваши деньги. Пожалуйста ознакомьтесь с ответом на 1ый вопрос из нашего [FAQ](https://blockchair.com/faq).
