### ISSUE TITLE
I've waited more than 2 days for a doge coin transaction

### ISSUE THREAD

**Issue by guillermoPg27** [Blockchair/Deleted-Issues#193]
Whats going on

**Comment by daria-blockchair** [comment]
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not store your money, we do not process transactions, and can not help to process your transaction faster. Please refer to our [FAQ (Q1)](https://blockchair.com/faq) and contact your wallet or exchange for more information.
