### ISSUE TITLE
Моя транзакция висит 14 суток без подтверждения, помогите. 

### ISSUE THREAD

**Issue by Papalesha71** [Blockchair/Deleted-Issues#194]
Помогите, моя транзакция висит 14 суток в мемпуле. 17756okwcjizJMaz3aix2fR591kNMVGF7k

**Comment by daria-blockchair** [comment]
Blockchair только показывает информацию о транзакциях, которые произошли в блокчейнах. Мы не предоставляем услуги кошелька, не обрабатываем транзакции и не храним ваши деньги. Пожалуйста ознакомьтесь с ответом на 1ый вопрос из нашего [FAQ](https://blockchair.com/faq).
