### ISSUE TITLE
Onaylanmamis transfer

### ISSUE THREAD

**Issue by gamesavas** [Blockchair/Deleted-Issues#199]
Gönderdiğim transfer işlemi 2 gündür onaylanmadi. Bu konu hakkinda madurum bu islem bir an once cozume ulaşsin lutfen
![Screenshot_20210310-142317_Chrome](https://user-images.githubusercontent.com/80398484/110629145-e8841a00-81b4-11eb-9fd3-9d0314aa677d.jpg)

**Comment by firadenqi** [comment]
Benimde aynı sorun var lütfen sorunumuzu giderin
