### ISSUE TITLE
Accidently send 3.7239132 BCH to localbitcoins.com BTC wallet

### ISSUE THREAD

**Issue by sampuk** [Blockchair/Deleted-Issues#23]
Hi,

I have accidently sent 3.7239132 BCH to localbitcoins.com BTC address. Is there a way for me to recover that missing BCH back to my BCH wallet.

Below is the transaction hash:
https://blockchair.com/bitcoin-cash/transaction/c9e702fc2a78eeaaae8df9bf9c6b499156c4b672305f2a90b385515f744eb013

Localbitcoins.com BTC address:
16xb8nQmacYXEYBB8Geh9Mtgfigqwzs7GF

Really need your help to recovery it.

Thank you.

**Comment by ghost** [comment]
I also have a similar problem. Bicoins send by bitcin cash, but never received at the endpoint
