### ISSUE TITLE
нужно вернуть биткоины 

### ISSUE THREAD

**Issue by Azazello2** [Blockchair/Deleted-Issues#306]
отправил депозит , хочу вернуть его , но как не знаю. Эти люди обманули , представились аналитиками

**Comment by daria-blockchair** [comment]
Dear @Azazello2,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.
Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

Thank you for understanding.

Best regards
