### ISSUE TITLE
https://www.coinbase.com/accounts/5ff7f767-2d87-5675-a586-d2709b59cc65

### ISSUE THREAD

**Issue by ampon0001** [Blockchair/Deleted-Issues#313]
395gsp9DTN5oJTFHQP4p47ToH5qRPi4N5X

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q3) and contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
