### ISSUE TITLE
سلام برای ارسال معامله ب من کمک کنید

### ISSUE THREAD

**Issue by mohammadpourzaker** [Blockchair/Deleted-Issues#318]
من به کمک نیازدارم 0.0065 BTC 
TxID
be70201382546c4a3e2f0ed88104570dc0a31846fb409aeae233117c3e775115
این آدرس گیرنده
bc1qn69n35hlve89hrxg7sp649lkp4fzz7xwvcpyy است

**Comment by daria-blockchair** [comment]
Hi @mohammadpourzaker ,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
The transaction [be70201382546c4a3e2f0ed88104570dc0a31846fb409aeae233117c3e775115](https://blockchair.com/bitcoin/transaction/be70201382546c4a3e2f0ed88104570dc0a31846fb409aeae233117c3e775115) is confirmed. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
