### ISSUE TITLE
395gsp9DTN5oJTFHQP4p47ToH5qRPi4N5X #583

### ISSUE THREAD

**Issue by ampon0001** [Blockchair/Deleted-Issues#319]
395gsp9DTN5oJTFHQP4p47ToH5qRPi4N5X Blockchair/Deleted-Issues#316

_Originally posted by @ampon0001 in https://github.com/Blockchair/Blockchair.Support/issues/580#issuecomment-894666179_

**Comment by daria-blockchair** [comment]
Hi @ampon0001,  
Blockchair only provides blockchain search and analytics services. 
Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains.

Thank you for understanding.

Best regards
