### ISSUE TITLE
Hi, I deposited about $ 193 USDT in the bitpie wallet a few hours ago, but now I want to send it to another wallet, unfortunately I can not send it, it does not have the send option and I can not withdraw my money from this bitpie wallet, please help me  How to withdraw my money from bitpie wallet, thanks

### ISSUE THREAD

**Issue by faree321** [Blockchair/Deleted-Issues#320]
Hi, I deposited about $ 193 USDT in the bitpie wallet a few hours ago, but now I want to send it to another wallet, unfortunately I can not send it, it does not have the send option and I can not withdraw my money from this bitpie wallet, please help me  How to withdraw my money from bitpie wallet, thanks

**Comment by daria-blockchair** [comment]
Hi @faree321,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
  
Best regards
