### ISSUE TITLE
خالی کردن کیف پولم

### ISSUE THREAD

**Issue by elyasy0** [Blockchair/Deleted-Issues#321]
از کیف پولم مبلغ 0,0057بیت کویین برداشت شده

**Comment by elyasy0** [comment]
چطور بتونم پولم رو برگردانم

**Comment by elyasy0** [comment]
چگونه پولم به کیف برگشت داده میشه

**Comment by daria-blockchair** [comment]
Hi @elyasy0,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
  
Best regards
