### ISSUE TITLE
Missed BTC sended

### ISSUE THREAD

**Issue by ronyr0424** [Blockchair/Deleted-Issues#322]
Last month July 29 I send 0.00057722 BTC to my friend using a QR Code, the transaction was confirmed, but my friend never receive the BTCs, when I come to the transaction details now I see that appear a different receive addres, not the same I read from the QR of my friend, What happen? Anybody can tell me?

**Comment by daria-blockchair** [comment]
Hi @ronyr0424,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
  
Best regards
