### ISSUE TITLE
cancel a transfer, before finishing the confirmations

### ISSUE THREAD

**Issue by evigra** [Blockchair/Deleted-Issues#323]
Yesterday someone made a transfer from my account. You can see how the confirmations were being authorized. without being able to get my money back.

Someone stole from me from this wallet.
LRSqPAGjrUaBqaZcEHNvgBadCfnUu4ZPso

This is the transaction
https://api.blockchair.com/litecoin/dashboards/transaction/3e3e1e2e851b13f1f2f435524f3ce2728132faef65ae31dcb58199ef09abde6f

Your IP 18.219.140.132

From this machine
http://ec2-18-219-140-132.us-east-2.compute.amazonaws.com/

**Comment by daria-blockchair** [comment]
Hi @evigra,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
 
Best regards
