### ISSUE TITLE
Transaction refund

### ISSUE THREAD

**Issue by nathanpham723** [Blockchair/Deleted-Issues#347]
Hi, i think i have been scammed. This man had linked me to moonpay in order to get a profit from bitcoin. I would like to hopefully get my money back if that is possible.

Kind Regards ,
Nathan

**Comment by Panda1228** [comment]
I have a huge problem, and I need help immediately please. Block Chair has been taken my Bitcoin, Lithcoin and Bitcoin Cash without any permission from me. They're usually pulling it only on Tuesday from my 3 accounts and they have taken 879, 748 of my Bitcoin alone, 277,000 of my Lithcoin and I have not been able to verify Bitcoin Cash yet. I have been collecting all of these for the last 5-7 years and I was in the process of getting a lawyer to help me Cash out. Well they have given it to many people who I have not a clue who they are and I still have 52,000 just Bitcoin and the app will not let me move it to my Crypto Wallet, where I thought it was going to begin with. How do I get the rest of my Bitcoin before they give it away. I want all of my coins refunded immediately and I have emailed them to stop sending them out and to reverse the transactions immediately and put in my wallet address.

**Comment by Panda1228** [comment]
That's funny because I posted pictures of the activity and the amounts of
DEPOSITS MADE !!!
I am getting a lawyer and the State Attorney's Office is going to be
involved also. Along with the FBI.
Thanks for the heads up.

**Comment by BalasubasTagago** [comment]
> I have a huge problem, and I need help immediately please. Block Chair has been taken my Bitcoin, Lithcoin and Bitcoin Cash without any permission from me. They're usually pulling it only on Tuesday from my 3 accounts and they have taken 879, 748 of my Bitcoin alone, 277,000 of my Lithcoin and I have not been able to verify Bitcoin Cash yet. I have been collecting all of these for the last 5-7 years and I was in the process of getting a lawyer to help me Cash out. Well they have given it to many people who I have not a clue who they are and I still have 52,000 just Bitcoin and the app will not let me move it to my Crypto Wallet, where I thought it was going to begin with. How do I get the rest of my Bitcoin before they give it away. I want all of my coins refunded immediately and I have emailed them to stop sending them out and to reverse the transactions immediately and put in my wallet address.

Hey, I am scammed more than $2000 and I have been searching and seeking help too.🥺
