### ISSUE TITLE
Pending transaction 

### ISSUE THREAD

**Issue by Chiderailo** [Blockchair/Deleted-Issues#364]
Bitcoin was sent but hasn’t been received for days now. 
The receiving address is 3FEMskpwVKme36MFVGsdj9iZBe5XH3br5F

the hash is 
589812f4d2496619d3f8911f3b483a4ef535df94a48adbc667aaebe8c30567ca

Kindly resolve this

**Comment by daria-blockchair** [comment]
Hi @Chiderailo ,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. The transition [589812f4d2496619d3f8911f3b483a4ef535df94a48adbc667aaebe8c30567ca](https://blockchair.com/bitcoin/transaction/589812f4d2496619d3f8911f3b483a4ef535df94a48adbc667aaebe8c30567ca) is confirmed.  Please contact your receiving wallet or exchange for more information.
 
Thank you for understanding.
