### ISSUE TITLE
SCAM!  SCAM! SCAM!

### ISSUE THREAD

**Issue by 75taylor** [Blockchair/Deleted-Issues#370]
Who do I need to speak to regarding a scammer that stole money from me tonight pretending to be someone they were not??  $1000 to be exact.  I have reported it and doing a police report in the morning.

**Comment by Bloodmone** [comment]
I mad a payment to a scammer account how can I get the refund

**Comment by cipsyali** [comment]
bende dolandırıldım nasıl yardım alabilirim lütfen yardım edin.
D9sgrLbqU7DQsvx3V1sY4eR9jNU3xwUiC6
26,054.10000000  DOGE
6.357,02  ABD Doları

**Comment by cipsyali** [comment]
eb9abba93d040a0249ea36d570104dcf006c8b1df284817da7be2501a15b6a04

**Comment by Bloodmone** [comment]
Okay hold I would get back to you
