### ISSUE TITLE
Не пришли деньги на счет 

### ISSUE THREAD

**Issue by Privetik22225** [Blockchair/Deleted-Issues#380]
5517ec68165a571a44737d186e6683e2f534bcc06d84585369533984dea6d5f7
Помогите решить вопрос, на счет не пришли

**Comment by daria-blockchair** [comment]
Hi @Privetik22225,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. 
The transaction [5517ec68165a571a44737d186e6683e2f534bcc06d84585369533984dea6d5f7](https://blockchair.com/bitcoin/transaction/5517ec68165a571a44737d186e6683e2f534bcc06d84585369533984dea6d5f7) is confirmed. Please contact your receiving wallet or exchange for more information.
