### ISSUE TITLE
Ошибочный перевод

### ISSUE THREAD

**Issue by rofnik** [Blockchair/Deleted-Issues#407]
Сегодня 14.01.22 19:41 произошёл перевод с моего кошелька по случайности на blockchaer Монета DOGECOIN, помогите разобраться как мне вернуть обратно эту монету на свой кошелёк?

**Comment by daria-blockchair** [comment]
Hi @rofnik,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
