### ISSUE TITLE
ошибочный перевод денег

### ISSUE THREAD

**Issue by Maksnemez** [Blockchair/Deleted-Issues#408]
скопировалась не правильная ссылка для перевода dogecoim 411 , можно ли их вернуть?

**Comment by daria-blockchair** [comment]
Hi @Maksnemez,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
