### ISSUE TITLE
I transfer to a rong persone

### ISSUE THREAD

**Issue by Abdsaqahtan** [Blockchair/Deleted-Issues#411]
I have developed a friend's user but when converting I am surprised that the user is different

**Comment by daria-blockchair** [comment]
Hello, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
