### ISSUE TITLE
Assets of blocked industries

### ISSUE THREAD

**Issue by flb1364** [Blockchair/Deleted-Issues#412]
Baba, greetings and best regards for your service, dear friend. I want to know how to return the blocked assets. Can you do me a favor?

**Comment by joani24** [comment]
> Baba, saudações e melhores cumprimentos pelo seu serviço, querido amigo. Quero saber como devolver os ativos bloqueados. Você pode me fazer um favor?

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
