### ISSUE TITLE
Rossz crypto pénztárca cím

### ISSUE THREAD

**Issue by Buckaa** [Blockchair/Deleted-Issues#413]
Üdvözletem rossz crypto pénztárca címet adtam meg BCH helyett BTC cimet irtam a freebitcon kiutalásomhoz.

**Comment by daria-blockchair** [comment]
Hi @Buckaa,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q5) and contact your wallet or exchange for more information.
 
Thank you for understanding.
