### ISSUE TITLE
Help me, Wrong wallet address 

### ISSUE THREAD

**Issue by JamesHorse** [Blockchair/Deleted-Issues#415]
Help me! I send BTC to the wrong wallet! How can I get a return??

**Comment by daria-blockchair** [comment]
Hi @JamesHorse,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange
 
Thank you for understanding.
