### ISSUE TITLE
 Помогите, пожалуйста

### ISSUE THREAD

**Issue by kcana12513** [Blockchair/Deleted-Issues#416]
10 ноября 2021 с криптонатора перевела биткоины. На кошельке 0. 
Получить выписку из кошелька: Адрес кошелька:
15vwg7pKoz7BrzMpKJN6VcsbGXhKsohuz6
Ошибка в адресной опечатке или определенном блокчейне не поддерживается. Что это значит? Спасибо.

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
