### ISSUE TITLE
netcoins withdrawal to wallet never arrived  transaction hash not found. https://blockchair.com/ripple/transaction/3241088DDFA9DE738E6E7654EC0ED05567F6314368A5AF27EED9180BE007136F?from=netcoins HELP

### ISSUE THREAD

**Issue by RD456** [Blockchair/Deleted-Issues#417]

**Comment by daria-blockchair** [comment]
Hi @RD456! Unfortunately, Blockchair does not support the full history of Ripple. We store only the data about the transaction that happened up to 2 months ago. 
Although, I've checked other XRP explorers and it seems that the hash of the transaction is incorrect. Please double-check the tx hash. For more information please contact your wallet or exchange.
