### ISSUE TITLE
Fraud transaction

### ISSUE THREAD

**Issue by TechnoHorizen** [Blockchair/Deleted-Issues#418]
Hello can you please help me with this transaction. The person is a scam.
Here is this adress: addr1qygxfpme8sx39lltf7lgkgh82n4k6e4xh2ya7ddmzxukfxcyz2l8euykug3t8agax5mktnfjml8qrvs5727sk49whs3s4m5ek8
Here is the txHash : 5cd00410fbaf45ac88feb34be00dde96646e4e0624d5d9d742ed49a692aed20b

Please help me back recovering my Ada.

**Comment by daria-blockchair** [comment]
Hi @ytarsha,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. We are sorry to hear that you've been scammed. If you want to know whether there is still a chance to get your funds back and to discuss the security of your account, please contact your wallet or exchange.
 
Thank you for understanding.
