### ISSUE TITLE
My BTC was stolen from my wallet

### ISSUE THREAD

**Issue by jackhandsome21** [Blockchair/Deleted-Issues#419]
![Screenshot_2022-01-10-22-10-41-642_com wallet crypto trustapp](https://user-images.githubusercontent.com/97478771/148840093-5df77d19-2d98-4795-9727-be5cb1244d9a.jpg)
my wallet address was stolen from my wallet bc1qttcmkre5gv6lnp4jxs3j2ftgyur9c5nhwssrvp transferred to the address 1FTtWdBwrrqervippHTvUSbEaztueUd9Ab transaction hash code : 7b580e61fb85fcd2f85b9f8d46d16b965bf7996371642ef11e5a5cdcf0919ecb

**Comment by daria-blockchair** [comment]
Hi @jackhandsome21,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
