### ISSUE TITLE
my coins did not come

### ISSUE THREAD

**Issue by fsh777** [Blockchair/Deleted-Issues#433]
![image](https://user-images.githubusercontent.com/86628211/162395370-aa95ba97-7865-4fcf-a011-dedb7dd10f5a.png)

3DKrH8JETUii6TBWd6zsrijkLPJd8gk8Wd

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.
 
Thank you for understanding.
