### ISSUE TITLE
scam

### ISSUE THREAD

**Issue by shirmel40** [Blockchair/Deleted-Issues#444]
i need my money back

**Comment by JohnnyMatos** [comment]
Hi my name is Jhonny this was my last transaction there was where they scammed me, 

this was my last transaction

687261d22025adf25d9288ac6b6fcfd97890c30b16b8104bb346f9d377e0eb04  

I need your help pleace, my Gmail Johnnymatos5182@gmail.com

**Comment by shirmel40** [comment]
y is this sent to me

**Comment by JohnnyMatos** [comment]
What should I do to get your answer?

**Comment by JohnnyMatos** [comment]
I was scammed and I wanted to know if I can get my money back I need to
know please I will leave you the transfer number and the wallet to which I
made the transfer.

Wallet: bc1q9tga977qyvmdlaxhf3t06clnmg59t6p0sq5gct

Transfer number:
d4b78544657e46e2448e11421aeb2857b2c31f3ae036b55458f5eae9b7180e9d

What should I do to get your answer?

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
