### ISSUE TITLE
воруют крипту с акаута

### ISSUE THREAD

**Issue by 89087573742** [Blockchair/Deleted-Issues#445]
Transaction hash:[158aeab83822f5bca14abe0099f4901ce7b75df4e4cde93ec9e611025aa9f723](https://blockchair.com/ru/bitcoin/transaction/158aeab83822f5bca14abe0099f4901ce7b75df4e4cde93ec9e611025aa9f723)  адрес мошенников

**Comment by shakibaei65** [comment]
سپاس و درود 
اشباه شده شده ی نشده بد افزار هستش باز نکنید

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
