### ISSUE TITLE
Preciso recuperar meu bitcon por favor

### ISSUE THREAD

**Issue by Branca05** [Blockchair/Deleted-Issues#450]
Preciso recusar meu bitcon O endereço não está mas ativo ativobc1q02etawc4sdf0d8nj74g6rm08xd30yq968fnsmu

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
