### ISSUE TITLE
returnare monede/ frauda

### ISSUE THREAD

**Issue by ioanar99** [Blockchair/Deleted-Issues#451]
Bitcoin trimis la adresa greșită
returnati monedele la adresa din care au fost trimise
1HnFW1CiA5mDKGXyYFceLrEQLY6Y6i9kHQ
Proprietarul adresei este un escroc și monedele au fost furate. Jetonul este returnat la aceeași adresă

vreau verificarea tuturor tranzactiilor mele si primirea banilor inapoi

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
