### ISSUE TITLE
Paribu bch hesabima gömderim yapmadiniz

### ISSUE THREAD

**Issue by Sabri44** [Blockchair/Deleted-Issues#453]
Merhaba 17 mayista kazandigim 0.000372 bch bakiyemi,sisteminize kaydettigim paribu Bch hesabima göndermediniz.mevcut bakiyemi kayıtlı Bch cüzdanıma gönderebilirmisiniz?

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.

**Comment by George43566** [comment]
1F3VuWc77fcwG3keVwe3JvgJ94EzqJDvvZ

**Comment by George43566** [comment]
Send my bitcoin  here
