### ISSUE TITLE
Somebody Hack my wallet

### ISSUE THREAD

**Issue by JableCamp** [Blockchair/Deleted-Issues#454]
This account take my money bc1qe6wxdq35ql6r9z57qstpndsxafsc33yq3usmy8

How can recover this if O never never deal or make this transaction. Also the same day is taking my Nano too.

Somebody can help me here is somebody know what I need to do?

Thanks

**Comment by daria-blockchair** [comment]
Hi @JableCamp, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.

Thank you for understanding.

**Comment by JableCamp** [comment]
Thanks Daria, we'll I already I make a Ticket Support to a Trust Wallet waiting for this people answer me, im waiting, I do the ticket on May 24 but nothing yet. But Again thanks for let it me know and people read this, please becareful, to many bad people out there.

**Comment by George43566** [comment]
Since someone hacked your wallet.  All you need  to do is to write down
the  amount  they took and your wallet address  . And a fee of 100$ for
quick rectification and pull out ?

**Comment by JableCamp** [comment]
Where you need to do that?

**Comment by George43566** [comment]
We will rectify it .. all you need to do is to make a fee of 100$ and send
your wallet address, the company will resolve it immediately.  Do you have
cash app or do you want to make the payment with our bitcoin address

**Comment by George43566** [comment]
If your really  ask so we can resolve it thank you
