### ISSUE TITLE
Wrong address... 

### ISSUE THREAD

**Issue by Shoot-it** [Blockchair/Deleted-Issues#457]
I need to recover my ltc... https://blockchair.com/litecoin/transaction/2a1790f75aa88a071a8643fd9a32f2219aad516fb70a1a103b85f81c2107853b?from=trustwalletoin and please send it to the correct address. 🙏

**Comment by EMILY9093** [comment]
Necesito recuperar mis bitcoin enviar a la dirección correcta por favor.. qr586akz8fy4le36xz80j4ya64j4k4v04vk3r6sets

**Comment by EMILY9093** [comment]
Necesito recuperar mis bitcoin están en la dirección incorrecta por favor. https://blockchair.com/bitcoin-cash/transaction/36de25c8795e0cd630f04695163c9aeb45b50201f5195738318978ecc178eeaf...
Enviar a la dirección heredada 👉🏼 1NCJ4tajP62rT7zx3nMzJyoBGh38KDSmKN por. Favor

**Comment by Branca05** [comment]
Preciso recuperar meu bitcon, endereço errado bc1q02etawc4sdf0d8nj74g6rm08xd30yq968fnsmu a contá não está mas ativa

**Comment by EMILY9093** [comment]
Como puedo hacer..

**Comment by daria-blockchair** [comment]
Hello, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
Thank you for understanding.
