### ISSUE TITLE
3Gyuy5zKPAtQDJfExMdCL6fYWt2YsVoeqHn  help help!!!!

### ISSUE THREAD

**Issue by alixette** [Blockchair/Deleted-Issues#458]
**I was deceived by this person named Daniel Garcia who is in a company called FOREX BINARY OPTION INVESTMENT, he wants to return my wallet with the income, I invested $564.76 usd and I have not received my profit and he is asking me for more money to invest.... please help i'm super worried..!!!**

**Comment by daria-blockchair** [comment]
Hello, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
Usually when somebody asks you to send money to release a bigger amount is a scam. If you suspect fraud you can contact local authorities.
Thank you for understanding.
