### ISSUE TITLE
pomoc

### ISSUE THREAD

**Issue by Sylwester890** [Blockchair/Deleted-Issues#464]
witam mam problem czy jest sznsa odzyskaci pieniadze z bockachaira 508001231

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
Thank you for understanding.

**Comment by daria-blockchair** [comment]
Hi,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
Thank you for understanding.
