### ISSUE TITLE
Scam i lost all my bitcoins

### ISSUE THREAD

**Issue by Kaiafas93** [Blockchair/Deleted-Issues#473]
12zXiA8KbaknpedBDcrVeLHqJpmHVhZGuR

This recieved $555 from me and i didnt get back my investment.

**Comment by Kaiafas93** [comment]
How to do that can you help me pls

**Comment by Kaiafas93** [comment]
Alright

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kaiafas93** [comment]
How to do it

**Comment by Kaiafas93** [comment]
Which words is all about can i use here

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Kaiafas93** [comment]
Its empty

**Comment by Kaiafas93** [comment]
How to do it

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
