### ISSUE TITLE
Withdraw not receive me bitcoin 

### ISSUE THREAD

**Issue by fadihmouda11** [Blockchair/Deleted-Issues#480]
TXID:ba8239eca6d2a2abc3faae5634e606147393aab430ae4f01f3d6c4b80f72a21b

**Comment by fadihmouda11** [comment]
![Screenshot_20220615_000420_com huawei browser](https://user-images.githubusercontent.com/83560975/173689566-ad435bc4-1456-4f0f-9609-9466cfe55e5f.jpg)

**Comment by fadihmouda11** [comment]
![Uploading Screenshot_20220615_000410_com.huawei.browser.jpg…]()

**Comment by daria-blockchair** [comment]
Hi!
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
The transaction [ba8239eca6d2a2abc3faae5634e606147393aab430ae4f01f3d6c4b80f72a21b](https://blockchair.com/bitcoin/transaction/ba8239eca6d2a2abc3faae5634e606147393aab430ae4f01f3d6c4b80f72a21b) is confirmed. Please contact your wallet or exchange for more information.
