### ISSUE TITLE
Problem with transaction

### ISSUE THREAD

**Issue by lapinro14** [Blockchair/Deleted-Issues#481]
I would like to know why it takes time to be confirmed it's been 24 hours I haven't received the bitcoins

**Comment by Halex06** [comment]
Boas
Fiz uma transação há mais de 3 dia já param mais de 48h e até agora não tenho nada na minha conta gostava de saber o quê que se passa

**Comment by daria-blockchair** [comment]
Hello, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information.
Thank you for understanding.
