### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Oaktownbbb** [Blockchair/Deleted-Issues#482]
I need help im new to this btc blockchair i been tryin to get my btc address  Bitcoin transfer to my cash app bitcooins or anywhere so my funds can b safe can u please help Oakland762@gmail.com
[fd8cd389980d2a27fe94f11e6a46feacf70f572f96bf6bd827fba76c40ef5667_en_usd.pdf](https://github.com/Blockchair/Blockchair.Support/files/8838426/fd8cd389980d2a27fe94f11e6a46feacf70f572f96bf6bd827fba76c40ef5667_en_usd.pdf)

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
