### ISSUE TITLE
Пожалуйста помогите 🆘🙏

### ISSUE THREAD

**Issue by Oleg159russ** [Blockchair/Deleted-Issues#483]
Дело в том что я хотел пополнить кошелёк 
Но с другого сайта вывел Litecoin при этом указав кошелёк Bitcoin 
И все щас не знаю что делать ((( подскажите пожалуйста как можно исправить данную ошибку 
P.s хотел пополнить stake на нем скапировал номер кошелка в bitcoin и с договор сайта выбрал litacoin и указал ссылку bitcoin

**Comment by daria-blockchair** [comment]
Dear Oleg, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. If you want to know whether there is a chance to get your funds back, please contact your wallet or exchange.
 
Thank you for understanding.
