### ISSUE TITLE
Stolen dogecoin from wallet

### ISSUE THREAD

**Issue by IkechukwuDestiny** [Blockchair/Deleted-Issues#486]
On may 24th the dogecoin in my trust wallet account was moved out of my account without me performing any transactions.... Please help reverse this action thanks.

**Comment by daria-blockchair** [comment]
Hi!
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
Thank you for understanding.
