### ISSUE TITLE
Блог номер 740 913

### ISSUE THREAD

**Issue by Rusiyoo12** [Blockchair/Deleted-Issues#487]
Добрый день. Зависли биткоины подскажи пожалуйста что делать? Номер блока 740913

**Comment by Rusiyoo12** [comment]
Добрый день все не решился вопрос по поводу блока моего? Биткоины так не поступили на счёт

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information. 
You can check the status of your transaction by searching its hash on [blockchair.com](https://blockchair.com/). If the transaction is not confirmed yet, please refer to our [FAQ](https://blockchair.com/faq#q0). If the transaction is confirmed, please contact your wallet or exchange for more information and to find out when the funds will be credited to your account.

Thank you for understanding.
