### ISSUE TITLE
Проблема с зачислением

### ISSUE THREAD

**Issue by Black13666** [Blockchair/Deleted-Issues#490]
Не приходят отправленные средства на счёт помогите 
Вот мой хэш
14479f734c87e221f9cccd59b294cb5ab2abc3542d4bddd520a71b65857e2ad3

**Comment by Black13666** [comment]
> Не приходят отправленные средства на счёт помогите
> Вот мой хэш
> 14479f734c87e221f9cccd59b294cb5ab2abc3542d4bddd520a71b65857e2ad3

741 303 номер блока

**Comment by daria-blockchair** [comment]
Hi @Black13666,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 
The transaction [14479f734c87e221f9cccd59b294cb5ab2abc3542d4bddd520a71b65857e2ad3](https://blockchair.com/bitcoin/transaction/14479f734c87e221f9cccd59b294cb5ab2abc3542d4bddd520a71b65857e2ad3) is confirmed. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
