### ISSUE TITLE
MS3H7VdW1qGZXMmWdJUjwFY3eGTFZ3VPrU

### ISSUE THREAD

**Issue by Jaebradley23** [Blockchair/Deleted-Issues#509]
Still pending

**Comment by Jaebradley23** [comment]
Doesn't show up anything at all

**Comment by Jaebradley23** [comment]
But yet I sent 30 bucks to that ltc wallet

**Comment by daria-blockchair** [comment]
Hi! If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.
Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information. 
Thank you for undertsanding.
