### ISSUE TITLE
Find exactly where your money went on Blockchair

### ISSUE THREAD

**Issue by Craddock7** [Blockchair/Deleted-Issues#526]
How do I move my money to buy other coins on blockchair

**Comment by Passion4866** [comment]
> How do I move my money to buy other coins on blockchair

**Comment by ZHANARBEK09** [comment]
Как я могу отправить BTC на Binance?

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, and we do not store your money. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
