### ISSUE TITLE
I can’t access my coincola account

### ISSUE THREAD

**Issue by Jaymesmako** [Blockchair/Deleted-Issues#535]

**Comment by Jaymesmako** [comment]
Blockchair/Blockchair.Support#918

**Comment by daria-blockchair** [comment]
Hi,
 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
