### ISSUE TITLE
BLockchair

### ISSUE THREAD

**Issue by dustosohappy25** [Blockchair/Deleted-Issues#558]
i want to know what the in the world is going on here because i believe i am doing every thing wrong here because ive gotten nowhere and feel like ive done nothing here and wantimg to be able to have done some thing by now/.

**Comment by daria-blockchair** [comment]
Hi, 

Blockchair only provides blockchain search and analytics services, so there is nothing we can do to help you with your payments. Please contact your wallet or exchange for more information.
 
Thank you for understanding.
