### ISSUE TITLE
Confirmations 

### ISSUE THREAD

**Issue by BandlifeP** [Blockchair/Deleted-Issues#589]
I have 827 confirmations but no money has sent ! What’s going on? I need a refund

**Comment by Margaretjane038** [comment]
It happened to me too thankful for Blackhathacker111 who helped me on telegram message him too

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
