### ISSUE TITLE
nothing arrived at my wallet

### ISSUE THREAD

**Issue by benjipan** [Blockchair/Deleted-Issues#590]
The transaction with the Hash: 95a9814379fc0fea1d235e58551ee28d75c7ae1be2582baa6c39cf7a37eb7fba
never arrived at my wallet.
I need realy help, the support from Myzelium is not doing anything

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
