### ISSUE TITLE
Deposito confirmado, no llego a su destino

### ISSUE THREAD

**Issue by Murci50** [Blockchair/Deleted-Issues#592]
![Captura de pantalla 2023-02-20 021801](https://user-images.githubusercontent.com/126291495/221292259-210021e7-aaf6-4a87-9b58-5127ba93c454.png)

Buenas, este depósito no llego a su destino, aun estando bien el numero de billetera, y poniendo confirmado en el recibo, ¿Que puede suceder de porque no lo he recibido?
Gracias.

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
