### ISSUE TITLE
Здравствуйте,  я перевёл деньги на другую Крипту но деньги не поступили уже давно , я не могу эти деньги ввести из вашего блокчейра

### ISSUE THREAD

**Issue by ZHANARBEK09** [Blockchair/Deleted-Issues#593]

**Comment by Henkzonfire** [comment]
Здравствуйте, я перевёл деньги на другую Крипту но деньги не поступили уже давно , я не могу эти деньги ввести из вашего блокчейра

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to blockchair support who helped me on telegram message them on telegram this their link https://t.me/blockchairsupport

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
