### ISSUE TITLE
My $1200 payment has not been received by my friend, it was confirmed on BLOCKCHAIN. 

### ISSUE THREAD

**Issue by Acpowell123** [Blockchair/Deleted-Issues#594]
Where did my payment go? This is the third payment he has not received!
How much longer?
It has been 2 days.
Here is confirmation:
![Screenshot_20230224-081851](https://user-images.githubusercontent.com/126274730/221235330-4d2930a2-b260-433a-9c66-72032eebfed2.png)

3afe0282aa872b3d519e3c024ba24154d94ee0f526cfabceaf83fe438b0f8877

**Comment by Acpowell123** [comment]
What language is this, and what does it mean, Please?

**Comment by Margaretjane038** [comment]
Same thing happened to me don’t believe anyone only a support helped me and I got all my $8000 back on discord message them Bitcoin.comsupport#2333 that’s their name on discord

**Comment by Margaretjane038** [comment]
And be quick about it

**Comment by Margaret034** [comment]
I was scammed almost 39k$ trying to invest thankGod I found a real person Elon Musk I gained back 100k$ in just a day message him 

https://www.facebook.com/profile.php?id=100088157787230

**Comment by Henkzonfire** [comment]
Damn I imagine how much you’ve lost before I finally met you different lie will come up to you don’t fall for it report this case fbi officers who helped me on telegram message him on telegram::FbiAroundYou

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
