### ISSUE TITLE
bit coin transfer

### ISSUE THREAD

**Issue by rcozza21** [Blockchair/Deleted-Issues#595]
hello ive been waiting now over 20 hours for a small bit coin transfer to go thru.  the
 txid  cd203782416c590ef1ab5c87585518b8d0898731d1caef653113b21ca40078c6

receiving wallet address is  36jq7iiiVsxQMwrKxstQS786FizTNY4KSk

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to blockchair support who helped me on telegram message them on telegram this their link https://t.me/blockchairsupport

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
