### ISSUE TITLE
Where is my money

### ISSUE THREAD

**Issue by PatryQ3254** [Blockchair/Deleted-Issues#598]
when the money will reach the address bc1q0rvjh5p6rynv78lujquxl4kxldm43t4pwd38q9 I sent it almost 2 days ago and I'm still waiting for a refund or you would send my 1600 PLN to this addres

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information.

Thank you for understanding.
