### ISSUE TITLE
Swap my assets 

### ISSUE THREAD

**Issue by nimrodotsile** [Blockchair/Deleted-Issues#599]
I can't receive my assets from blockchair to my Bitcoin app,can you please help me with that.

**Comment by Henkzonfire** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me message him on telegram his telegram username is Blackhathacker111

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
