### ISSUE TITLE
Transfer assets from Bitcoin to cropty account 

### ISSUE THREAD

**Issue by nimrodotsile** [Blockchair/Deleted-Issues#601]
https://snowtrace.io/tx/0x7b56158c20bea43e97c90e1699ff04ad137d938f629e40cd9bf87f6a46f99f8d

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
