### ISSUE TITLE
Frozen

### ISSUE THREAD

**Issue by johnsmith12colin** [Blockchair/Deleted-Issues#605]
I sent my coin from trust wallet to paxful and it was frozen

**Comment by daria-blockchair** [comment]
Hi @johnsmith12colin ,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information.

Thank you for understanding.
