### ISSUE TITLE
Нет пополнения битка

### ISSUE THREAD

**Issue by ezamov1103** [Blockchair/Deleted-Issues#611]
Нет пополнения битка  ID: 734801

**Comment by daria-blockchair** [comment]
Hi @ezamov1103,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please refer to our [FAQ](https://blockchair.com/faq#q0) and contact your wallet or exchange for more information.

Thank you for understanding.
