### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kassie2023** [Blockchair/Deleted-Issues#613]
Hello I need help regarding my bitcoins I'm having issues I got payed from a casino they sent me bitcoins but can't locate then I have the hash ID or transaction ID what can I do

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
