### ISSUE TITLE
Scam Charge

### ISSUE THREAD

**Issue by Misiere** [Blockchair/Deleted-Issues#617]
Hello,

I wanted to inquire if there are any methods to reverse the transaction that was sent to a fraudulent, incorrect copy of another address. I cannot find a way to contact the other end of this transaction, and the actual site the crypto was attained through cannot do anything.

Thank you

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.

Thank you for understanding.
