### ISSUE TITLE
Transação cancelada

### ISSUE THREAD

**Issue by AnaSantos1979** [Blockchair/Deleted-Issues#626]
Boa noite! A minha transação 3QwsNfGRX52GxHBFs8MbKoX4Yk7De8TbcQ
Foi cancelada e o dinheiro não foi reposto na minha carteira.
Meu email analuzpsantos@gmail.com

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
