### ISSUE TITLE
my bitcoin is taking forever to get to my address

### ISSUE THREAD

**Issue by miguelllI** [Blockchair/Deleted-Issues#646]
i bought bitcoin via moon pay 2 days ago and still havent recieved it yet/ Transaction Hash 480580676c5819a437d8ed8f9ae95153f37
<img width="900" alt="Screenshot 2023-05-08 220409" src="https://user-images.githubusercontent.com/132970504/236983506-72c8e3af-1a98-45eb-8b4b-7a31dd35e42a.png">
2712ad68656de22920c723c025f3a

**Comment by daria-blockchair** [comment]
Hi @miguelllI, 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately.

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

Miners process transactions based on the transaction fee attached to a transaction. It can take quite some time before your transaction is processed: several minutes, hours, sometimes several days, and in some cases, it seems your transaction will never be processed!

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block more quickly.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

Thank you for understanding.
