### ISSUE TITLE
Victim of scam 

### ISSUE THREAD

**Issue by Jacquielh157** [Blockchair/Deleted-Issues#65]
I sent my bitcoin cash to Someone for services. I was a victim of scam. I did not receive anything. I need to cancel my payment and refund my bitcoin cash.

**Comment by Jacquielh157** [comment]
This link is not taking me to an active support page. I need to get in
contact with someone that can help me resolve my issue

**Comment by Har01d** [comment]
Please try this link once again: https://github.com/Blockchair/Blockchair.Support/blob/master/README.md
