### ISSUE TITLE
Withdrawal process 

### ISSUE THREAD

**Issue by Trylan123** [Blockchair/Deleted-Issues#650]
Hi here is my wallet id 2K2764NV2 it is a paper wallet and i want to import it and process the withdrawal. I  have made payments for it already more than what it was asking. I wi attached thw receipt and i need yo knoq how to complete the peocess. Please guide me photos and videos with step by step process should of be a big help. Thanks

Payment. 39wTXBHs5XivvZHpFyYg2baoDZPzB8mCBE

Wallet: 

bc1qfzmx32wjytknp6he5zftx5uxe6zaq005vq7r79

+d00dfa7f7efc4bc818b9e94806003cbdce5fac486c7f6ae159b2c815b0567d41

**Comment by daria-blockchair** [comment]
Hi @Trylan123,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.

**Comment by Cryptolord123** [comment]
> Hi here is my wallet id 2K2764NV2 it is a paper wallet and i want to import it and process the withdrawal. I have made payments for it already more than what it was asking. I wi attached thw receipt and i need yo knoq how to complete the peocess. Please guide me photos and videos with step by step process should of be a big help. Thanks
> 
> Payment. 39wTXBHs5XivvZHpFyYg2baoDZPzB8mCBE
> 
> Wallet:
> 
> bc1qfzmx32wjytknp6he5zftx5uxe6zaq005vq7r79
> 
> +d00dfa7f7efc4bc818b9e94806003cbdce5fac486c7f6ae159b2c815b0567d41

Message blackhathacker111 on telegram he helped me with the best process
