### ISSUE TITLE
Recieving

### ISSUE THREAD

**Issue by Levene09** [Blockchair/Deleted-Issues#656]
Have not uet revieved bitcoin i sent to my account in over 2weeks

**Comment by daria-blockchair** [comment]
Hi @Levene09,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
