### ISSUE TITLE
Была транзакция но потом сразу же пропала

### ISSUE THREAD

**Issue by Kit341** [Blockchair/Deleted-Issues#671]
Здравствуйте, было две транзакции на один кошелёк, одна и та же сумма, но почему-то пришла только вторая, а в первой выдаёт ошибку. 
По этой ссылке ошибка https://blockchair.com/bitcoin/transaction/0362823233618661c85730ca1321d32a1fb8fda401239bb4b09af29ab17eb399?from=trustwallet
Я получатель и насколько знаю биткоин списался

**Comment by daria-blockchair** [comment]
Hi @Kit341,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
