### ISSUE TITLE
Revealing the owner of crypto address

### ISSUE THREAD

**Issue by Redimanok** [Blockchair/Deleted-Issues#679]
I was scammed and want to reveal the identity of the person by providing the wallet address and trx id. Please help me out. Thanks

**Comment by daria-blockchair** [comment]
Hi @Redimanok,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Also, we don't have any information about the owners of the addresses or on which platform the address was registered.
Please contact your wallet or exchange for more information.

Thank you for understanding.
