### ISSUE TITLE
Transaction issue

### ISSUE THREAD

**Issue by Painisinsane** [Blockchair/Deleted-Issues#680]
Went to buy tokens and it shows That it was confirmed but no tokens anywhere .. even messaged dogetti to fix the issue and nothing has been done

**Comment by daria-blockchair** [comment]
Hi @Painisinsane,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
