### ISSUE TITLE
ฉันไม่ได้รับธุรกรรม ที่ส่งไป

### ISSUE THREAD

**Issue by Peepypy2532** [Blockchair/Deleted-Issues#693]
แฮชธุรกรรม:[93c39d99f7d8613f25539da8b119b3ea333671305781cbbe32c29f9c80226115](https://blockchair.com/litecoin/transaction/93c39d99f7d8613f25539da8b119b3ea333671305781cbbe32c29f9c80226115)
โปรดตรวจสอบด้วยคะ

**Comment by daria-blockchair** [comment]
Hi @Peepypy2532, 

The transaction is confirmed: https://blockchair.com/litecoin/transaction/93c39d99f7d8613f25539da8b119b3ea333671305781cbbe32c29f9c80226115.

Please note, Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please get in touch with your wallet or exchange for more information.

Thank you for understanding.
