### ISSUE TITLE
Devolución de dinero 

### ISSUE THREAD

**Issue by Leonar06** [Blockchair/Deleted-Issues#697]
Por favor llamarme q ya llevo una semana escribiendo q me
Llamen y nada nececito mi dinero

**Comment by lizet90** [comment]
Cómo hago para regresar mis bicoins

**Comment by lizet90** [comment]
Necesito reembolso de mis monedas

**Comment by Leonar06** [comment]
También ando detrás de ellos para q me devuelvan mi dinero Enviado desde mi iPhoneEl 25 ago 2023, a las 6:07, lizet90 ***@***.***> escribió:﻿
Necesito reembolso de mis monedas

**Comment by lizet90** [comment]
Realmente se puede recuperar el dinero?

**Comment by Leonar06** [comment]
Pero como se puede recuperar Enviado desde mi iPhoneEl 25 ago 2023, a las 14:37, lizet90 ***@***.***> escribió:﻿
Realmente se puede recuperar el dinero?





El vie, 25 de ago de 2023, 4:16 a. m., Leonar06 ***@***.***>

escribió:

**Comment by Leonar06** [comment]
Necesito q me devuelvan mis monedas a mi cartera 
Enviado desde mi iPhone

**Comment by Leonar06** [comment]
Q tal y cuanto cobra el por ayudar a recuperar mis monedasEnviado desde mi iPhoneEl 28 ago 2023, a las 12:25, MarkCuban6900 ***@***.***> escribió:﻿

Necesito q me devuelvan mis monedas a mi cartera Enviado desde mi iPhone

Sí, envíale un telegrama, él te ayudará a hacerlo https://t.me/Blackhathacker110

**Comment by Leonar06** [comment]
Llamarme en español att leonardo aguirre

Enviado desde mi iPhone

**Comment by daria-blockchair** [comment]
Hi,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and cannot help you get it back, unfortunately. Please contact your wallet or exchange for more information.

Thank you for understanding.
