### ISSUE TITLE
i didn't receive my bch in my wallet!

### ISSUE THREAD

**Issue by Justinyaa** [Blockchair/Deleted-Issues#734]
it says confirmed on my address nut the platform said they dont see it .. if anyone can tell me why ? or if someone can figure it out ill pay

**Comment by daria-blockchair** [comment]
> it says confirmed on my address nut the platform said they dont see it .. if anyone can tell me why ? or if someone can figure it out ill pay

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money. 
Please get in touch with your wallet or exchange for more information.
Thank you for understanding.
