### ISSUE TITLE
cüzdana yanlışlıkla gönderilen para.

### ISSUE THREAD

**Issue by ramazanhoca** [Blockchair/Deleted-Issues#747]
sayın admin d30a3cb6844b84e526dca0c2b07c5db58b2723818a5c95b101620a2af5f1fec1 işlem kimliğiyle gönderilen fon yanlışlıkla gönderilmiştir.aslında başka cüzdana bitcoin adresine gönderilmesi gerekirken buraya gönderilmiştir..ilgilenirseniz sevinirim..

**Comment by ramazanhoca** [comment]
Dear admin, the fund sent with the transaction d30a3cb6844b84e526dca0c2b07c5db58b2723818a5c95b101620a2af5f1fec1 was sent by mistake from the coinpayu site. I would be glad if you would be interested.

**Comment by daria-blockchair** [comment]
> Dear admin, the fund sent with the transaction d30a3cb6844b84e526dca0c2b07c5db58b2723818a5c95b101620a2af5f1fec1 was sent by mistake from the coinpayu site. I would be glad if you would be interested.

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction.

If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.
