### ISSUE TITLE
Cómo recupero mis fondos en btc estancados en la blockchair 

### ISSUE THREAD

**Issue by felix-salazar** [Blockchair/Deleted-Issues#749]
Hola quisiera que me guíen en recuperar mis fondos en la blockchair estancados o si se podrá nuevamente reenviar al destinatario, por qué mi billetera no la aceptó ya que el mínimo a recibir en btc fue otro monto y por lo tanto mis fondos se quedaron estancados, gracias por su atención y comprendan el tema 
Nuevamente agradezco de su colaboración al respecto

**Comment by daria-blockchair** [comment]
> Hola quisiera que me guíen en recuperar mis fondos en la blockchair estancados o si se podrá nuevamente reenviar al destinatario, por qué mi billetera no la aceptó ya que el mínimo a recibir en btc fue otro monto y por lo tanto mis fondos se quedaron estancados, gracias por su atención y comprendan el tema
> Nuevamente agradezco de su colaboración al respecto

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. 
If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange.
Thank you for understanding.

**Comment by felix-salazar** [comment]
Hola no ellos me dicen que no pueden hacer nada he estado insistiendo 😞, ya que no fue mi culpa ellos cambiaron el mínimo de 0.0002 a 0.0006 de un día para otro sin notificarle a sus clientes

**Comment by felix-salazar** [comment]
Requiero cambiar la dirección de billetera no existe la posibilidad para poder recibir esos btc estancados

**Comment by felix-salazar** [comment]
Y si almacenan el dinero por qué todavía siguen estancados
