### ISSUE TITLE
Bitcoin still on chain

### ISSUE THREAD

**Issue by Dirtbagcentral36** [Blockchair/Deleted-Issues#757]
My Bitcoin has failed to get 1 confirmation after almost 2 days on your blockchain. Is there anything we can do to get this to move please? Here's the screenshot of the hash 
![Screenshot_20231105-105453](https://github.com/Blockchair/Blockchair.Support/assets/149980658/64a186f7-4ef2-4fd7-b400-a67bb132abb2)

**Comment by daria-blockchair** [comment]
> My Bitcoin has failed to get 1 confirmation after almost 2 days on your blockchain. Is there anything we can do to get this to move please? Here's the screenshot of the hash ![Screenshot_20231105-105453](https://user-images.githubusercontent.com/149980658/280567638-64a186f7-4ef2-4fd7-b400-a67bb132abb2.png)

If you have been waiting for a long period for your transaction to be processed, the most likely reason is a low transaction fee.

You can contact your wallet or exchange to receive information about how to increase your transaction fee. 

Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.

For more information, please refer to our [FAQ](https://blockchair.com/faq/why): https://blockchair.com/faq/why.
