### ISSUE TITLE
Quero receber o meu investimento.

### ISSUE THREAD

**Issue by 02091945** [Blockchair/Deleted-Issues#847]
Quero pedir o meu investimento, como devo fazer???

**Comment by 02091945** [comment]
Como posso pedir o meu investimento

**Comment by daria-blockchair** [comment]
Hi @02091945, 
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
