### ISSUE TITLE
Epuremihai1977@gmail.com

### ISSUE THREAD

**Issue by mihaiepure1977** [Blockchair/Deleted-Issues#855]
Bonjour je vous envoie le relevé de mon portofoil de crypto

**Comment by mihaiepure1977** [comment]
> Bonjour je vous envoie le relevé de mon portofoil de crypto

**Comment by mihaiepure1977** [comment]
Je a fet la vérification avec 2 fa

**Comment by daria-blockchair** [comment]
Hi @mihaiepure1977,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
