### ISSUE TITLE
Wolfgang_ James Neufeld

### ISSUE THREAD

**Issue by 95531G** [Blockchair/Deleted-Issues#857]
2017 BTC except couple file pages stolen from my new t mobile devices by person above not sure how he got data from my device but he did at job both work
Well for me I'm healing while co workers helping their selves to my trust wallet stolen and then used my ATM card to Auth in wallet and is running crypto  as  me but all coin that has been moved is stolen by leach employees in sparks nv now it's fanning out to mafias Mexican etc all persons I was working with prison half way houses paroles so double compound tibula fibula fracture 
Layed on floor over hour waiting for employees to call 911 no call made until lunch bell rang and employees traffic lightly no words 
No help etc yeah they almost killed me So I want my crypto back at all any cost they are 13-15 persons ,no cost to  much 
SEAN BRENNAN

**Comment by Harrystarafk** [comment]
> 2017 BTC except couple file pages stolen from my new t mobile devices by person above not sure how he got data from my device but he did at job both work Well for me I'm healing while co workers helping their selves to my trust wallet stolen and then used my ATM card to Auth in wallet and is running crypto as me but all coin that has been moved is stolen by leach employees in sparks nv now it's fanning out to mafias Mexican etc all persons I was working with prison half way houses paroles so double compound tibula fibula fracture Layed on floor over hour waiting for employees to call 911 no call made until lunch bell rang and employees traffic lightly no words No help etc yeah they almost killed me So I want my crypto back at all any cost they are 13-15 persons ,no cost to much SEAN BRENNAN

They will never reply you on here and they can’t do anything I almost lost about 10 ethereum few days ago when my wallet got hacked and all my funds withdrawn but thanks to blackhathacker who helped me recover my coins from the scammers  message him on telegram https://t.me/Blackhathacker110
