### ISSUE TITLE
My xrp not recived

### ISSUE THREAD

**Issue by Cof7576** [Blockchair/Deleted-Issues#860]
My XRP not received in to my wallet after 7 hour ago please confo
![Screenshot_20240918-052051](https://github.com/user-attachments/assets/031656ac-af8c-4b0b-94fd-ac5f5f4d1f52)
rm [fast

**Comment by daria-blockchair** [comment]
Hi @Cof7576,
Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not store your money, and we cannot help you get it back, unfortunately. Blockchair does not process transactions, so we are unable to prioritize processing your transaction over other transactions.
Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
