### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by mrswart222** [Blockchair/Deleted-Issues#866]
Pay to address but never received my payment 2

**Comment by daria-blockchair** [comment]
> Pay to address but never received my payment 2

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.
Thank you for understanding.
