### ISSUE TITLE
This person stole my Bitcoin....after many confirmation I sent to him...who can help me

### ISSUE THREAD

**Issue by Khalifa119** [Blockchair/Deleted-Issues#870]
I sent more than $500+ Bitcoin to him and he never paid me...he lied to me that he didn't receive it and had been ignoring my messages on Whatsapp 😭 this about a month ago now...so I decided to find help from here or anywh
![Screenshot_20241104-063228](https://github.com/user-attachments/assets/f9688eaa-176d-47f0-b66f-04a3e93b9b37)
ere😭😭😭😭😔😔😔
![Screenshot_20241104-063228](https://github.com/user-attachments/assets/9a14474a-e505-4acf-9299-96665e6a661d)
![Screenshot_20241104-063210](https://github.com/user-attachments/assets/0b3942ab-f75c-4ba1-a242-9f02c836a23b)
[Wallet statement 1_1 2024-09-10 - 2024-11-03 (1).pdf](https://github.com/user-attachments/files/17614195/Wallet.statement.1_1.2024-09-10.-.2024-11-03.1.pdf)
![Screenshot_20241104-063228](https://github.com/user-attachments/assets/96e5486c-57d8-4c9f-be4e-118732510d8f)
![Screenshot_20241104-063210](https://github.com/user-attachments/assets/770a87f6-c064-4a1e-89eb-093cc79c35a3)
[Wallet statement 1_1 2024-09-10 - 2024-11-03 (1).pdf](https://github.com/user-attachments/files/17614196/Wallet.statement.1_1.2024-09-10.-.2024-11-03.1.pdf)

**Comment by daria-blockchair** [comment]
Hi @Khalifa119, 

We are sorry to hear about you being scammed. Unfortunately, we are not able to help get your money back. 

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we don't have any personal information about the owners of the addresses.

Irreversibility is one of the fundamental properties of blockchain technology. Once a transaction is included in a block, it is not possible to reverse the transaction. If you want to know whether there is still a chance to get your funds back, please contact your wallet or exchange. Blockchair does not process transactions, nor do we provide wallet services. We can not reverse transactions in public blockchains. No one can.

Thank you for understanding.
