### ISSUE TITLE
Need help retrieveing my stock

### ISSUE THREAD

**Issue by Arkman01** [Blockchair/Deleted-Issues#875]
I sent stock from my trust account to coinbase never received can I get some help shows transaction but got nothing I can see it in the transfered section

**Comment by Arkman01** [comment]
GBSX2XH6LTJVT5QUTMF7MUCOB6B4DJTTANWIMAJZSHJDOUVMA5FFMATT

**Comment by daria-blockchair** [comment]
Hi @Arkman01!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.

**Comment by Jaynelauren** [comment]
> I sent stock from my trust account to coinbase never received can I get some help shows transaction but got nothing I can see it in the transfered section

Hey @Arkman01 ,
If your issue hasn’t been resolved yet, I suggest contacting the support team for specialized assistance.
A support ticket has been created for you with ID CBW7638. Visit [Coinbase Wallet Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble in the bottom right to connect with an agent for quick help.
Thank you for your patience—I’m confident this will be resolved.
