### ISSUE TITLE
Need help speeding up my bitcoin transaction 

### ISSUE THREAD

**Issue by QueenRoyalee** [Blockchair/Deleted-Issues#876]
Need help speeding up my bitcoin transaction that was made over 3 hrs ago 934a158692b2bd421d3e2cecf074458568182ebe77845ed81c32898e9c1b3929
That is my transaction id information I retrieved from blockchain

**Comment by daria-blockchair** [comment]
Hi @QueenRoyalee! It seems that the transaction is confirmed: https://blockchair.com/bitcoin/transaction/934a158692b2bd421d3e2cecf074458568182ebe77845ed81c32898e9c1b3929

If your transaction fee is low, it might take some time before the transaction is included in a block. To have your transaction prioritized by miners over other transactions, you can attach a higher transaction fee to your transaction, incentivizing miners to include your transaction in a block quicker.

Some wallets support functionality to increase the transaction fee.
Please reach out to your wallet or exchange to find out what you can do to have your transaction processed faster.
