### ISSUE TITLE
Con transfer

### ISSUE THREAD

**Issue by Gera1973** [Blockchair/Deleted-Issues#878]
I made a transfer from my Robinhood account to my other XLM Coinbase account and I didn't put the memo and the money didn't come in.

**Comment by daria-blockchair** [comment]
Hi @Gera1973,

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
