### ISSUE TITLE
Wallet Problems

### ISSUE THREAD

**Issue by Cata-wq** [Blockchair/Deleted-Issues#879]
I bought bitcoins from Paybis, using addresses from this page, but my wallet says I didn't buy anything, since I want to withdraw the money invested. I spoke to Paybis support and they told me that since it was an external wallet I should talk to you. I will leave the links to the transactions, I await your responses. Thank you very much.
https://blockchair.com/bitcoin/transaction/08f65f49296263a452d835adc5edd721343ae549f11deacb8263a45b5ec82513?from=paybis
https://blockchair.com/bitcoin/transaction/0310d1fcb9e72720a13282b98b06820b131ba092fdee115e8e1eb39121ef869e?from=paybis

**Comment by Manuel292991** [comment]
No puedo acceder Ami billetera

**Comment by daria-blockchair** [comment]
Hi @Cata-wq!

Blockchair only displays information regarding transactions that happened in blockchains. We do not provide wallet services, we do not process transactions, we do not store your money, and we cannot help you get it back, unfortunately. Please contact the support of your wallet or exchange for more information.

Thank you for understanding.
